env:
  LEIN_ROOT: "true"
  CLOJARS_USERNAME: ENCRYPTED[!38aa86f130316e623511e9425d88bd2be2aaa109164328b2d0c90aea35ef0ebbc32a51e5ff5b805ec20ffe6cc6fe0723!]
  CLOJARS_PASSWORD: ENCRYPTED[!c43d6967c24f7fd8bf1b02f58e11e285316b288785dd56cd58c08291c2047aa935bde02b1f366e292d85c57b038acf48!]

task:
  arm_container:
    image: ubuntu:latest
  # only_if: $CIRRUS_TAG != ''
  only_if: "changesInclude('linux-arm64/*', '.cirrus.yml')"
  script: |
    DEBIAN_FRONTEND=noninteractive apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y curl git wget tar openjdk-21-jdk-headless build-essential cmake g++-12 gcc-12

    git submodule init
    git submodule update --init --recursive

    mkdir -p src/java/datalevin/dtlvnative/linux-arm64
    mkdir -p linux-arm64/resources/datalevin/dtlvnative/linux-arm64

    script/build
    cp src/*.so src/java/datalevin/dtlvnative/linux-arm64/

    curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod a+x lein
    mv lein /usr/local/bin/

    cd linux-arm64
    lein deps

    cd ../src/java
    java -jar ~/.m2/repository/org/bytedeco/javacpp/1.5.11/javacpp-1.5.11.jar datalevin/dtlvnative/DTLV.java

    cd ../..
    cp src/java/datalevin/dtlvnative/linux-arm64/*.so linux-arm64/resources/datalevin/dtlvnative/linux-arm64/

    cd linux-arm64
    lein run
    lein deploy clojars

task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  only_if: $CIRRUS_TAG != ''
  # only_if: "changesInclude('macosx-arm64/*', '.cirrus.yml')"
  script: |
    git submodule init
    git submodule update --init --recursive

    mkdir -p src/java/datalevin/dtlvnative/macosx-arm64
    mkdir -p macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64

    brew install leiningen libomp llvm

    script/build-macos
    cp src/*.dylib macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/

    cd macosx-arm64
    lein deps

    cd ../src/java
    java -jar ~/.m2/repository/org/bytedeco/javacpp/1.5.11/javacpp-1.5.11.jar datalevin/dtlvnative/DTLV.java

    cd ../..
    cp src/java/datalevin/dtlvnative/macosx-arm64/*.dylib macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/

    cd macosx-arm64
    lein run
    lein deploy clojars
