#!/bin/bash

rm -rf src/java/datalevin/dtlvnative/*.class src/java/datalevin/dtlvnative/macosx-arm64
rm macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/*

script/build-macos

cp src/*.dylib macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/

cd src/java
java -jar ~/.m2/repository/org/bytedeco/javacpp/1.5.12/javacpp-1.5.12.jar datalevin/dtlvnative/DTLV.java

cd ../..
cp src/java/datalevin/dtlvnative/macosx-arm64/*.dylib macosx-arm64/resources/datalevin/dtlvnative/macosx-arm64/

cd macosx-arm64
lein clean
lein deps
lein run
lein jar
