#!/bin/bash

set -eou pipefail

export SOEXT=.dylib

## build usearch

cd src/usearch

# Use LLVM CLang (v19) instead of Apple one (v16) to compile
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export LDFLAGS="${LDFLAGS:+$LDFLAGS }-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/libomp/lib -L/usr/local/opt/llvm/lib -L/usr/local/opt/libomp/lib"
export CPPFLAGS="${CPPFLAG:+$CPPFLAGS }-I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/libomp/include -I/usr/local/opt/llvm/include -I/usr/local/opt/libomp/include"

cmake \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER="$(brew --prefix llvm)/bin/clang" \
    -D CMAKE_CXX_COMPILER="$(brew --prefix llvm)/bin/clang++" \
    -D USEARCH_USE_FP16LIB=1 \
    -D USEARCH_USE_OPENMP=1 \
    -D USEARCH_USE_SIMSIMD=1 \
    -D USEARCH_BUILD_TEST_CPP=1 \
    -D USEARCH_BUILD_TEST_C=1 \
    -D USEARCH_BUILD_LIB_C=1 \
    -B build_release

cmake --build build_release --config Release

build_release/test_cpp
build_release/test_c

## build lmdb and dtlv

export OMP_LIB="-lomp"
export USEARCH_LIB="-Wl,-force_load,libusearch.a"

cd ..
make clean
make
